# Generated by Django 4.2.11 on 2024-08-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fts_app", "0016_notingusermap_signature_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="noting",
            name="signature_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
